{{- if eq .Values.gateway.type "oauth2-proxy" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "auth-gateway.gatewayName" . }}
  labels:
    {{- include "auth-gateway.labels" . | nindent 4 }}
  namespace: {{ .Values.keycloak.namespace }}
spec:
  type: {{ .Values.gateway.oauth2Proxy.service.type }}
  ports:
    - port: {{ .Values.gateway.oauth2Proxy.service.port }}
      targetPort: {{ .Values.gateway.oauth2Proxy.service.port }}
      {{- if eq .Values.gateway.oauth2Proxy.service.type "NodePort" }}
      nodePort: {{ .Values.gateway.oauth2Proxy.service.nodePort }}
      {{- end }}
      protocol: TCP
      name: http
  selector:
    {{- include "auth-gateway.selectorLabels" . | nindent 4 }}
{{- end }}
