{{- if eq .Values.gateway.type "oauth2-proxy" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth-gateway.gatewayName" . }}
  labels:
    {{- include "auth-gateway.labels" . | nindent 4 }}
  namespace:
stringData:
  ## Ref. https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview/#generating-a-cookie-secret
  OAUTH2_PROXY_COOKIE_SECRET: {{ randAlphaNum 32 | b64enc }}
{{- end }}
